linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - misspell
    - goimports
    - revive
    - gosec

linters-settings:
  govet:
    shadow: true
  goimports:
    local-prefixes: github.com/renegade-fi/golang-sdk

run:
  deadline: 5m

issues:
  exclude-use-default: false
