package api_types

// ApiExternalOrder is an order from outside of the darkpool, generated by a client
// requesting an external match
type ApiExternalOrder struct {
	// The mint (erc20 address) of the base asset
	// As a hex string
	BaseMint string `json:"base_mint"`
	// The mint (erc20 address) of the quote asset
	// As a hex string
	QuoteMint string `json:"quote_mint"`
	// The amount of the base asset to buy/sell
	Amount Amount `json:"amount"`
	// The side of the order
	Side string `json:"side"`
	// The minimum fill amount to cross the order at
	// Specified in units of the base asset
	MinFillSize Amount `json:"min_fill_size"`
}

// ExternalMatchBundle contains a match and a transaction that the client can submit on-chain
type ExternalMatchBundle struct {
	MatchResult  ApiExternalMatchResult `json:"match_result"`
	SettlementTx SettlementTransaction  `json:"settlement_tx"`
}

// ApiExternalMatchResult is the result of a request to generate an external match
type ApiExternalMatchResult struct {
	QuoteMint   string `json:"quote_mint"`
	BaseMint    string `json:"base_mint"`
	QuoteAmount Amount `json:"quote_amount"`
	BaseAmount  Amount `json:"base_amount"`
	Direction   string `json:"direction"`
}

// SettlementTransaction is an EVM transaction parameterization for settling an external match
type SettlementTransaction struct {
	Type string `json:"type"`
	To   string `json:"to"`
	Data string `json:"data"`
}
